# Generated by Django 6.0.3 on 2026-03-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("festivais", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="banda",
            name="festivais",
            field=models.ManyToManyField(
                related_name="festival", to="festivais.festival"
            ),
        ),
    ]
