# Generated by Django 6.0.3 on 2026-03-22 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ginasio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=25)),
                ("localizacao", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Membro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("nif", models.IntegerField()),
                (
                    "ginasio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ginasio.ginasio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("ptNumero", models.IntegerField()),
                (
                    "ginasio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ginasio.ginasio",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("hora", models.TimeField()),
                (
                    "membro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ginasio.membro"
                    ),
                ),
                (
                    "pt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ginasio.pt"
                    ),
                ),
            ],
        ),
    ]
