# Generated by Django 6.0.3 on 2026-04-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("grau", models.CharField(max_length=50)),
                ("ects_totais", models.IntegerField()),
                ("duracao", models.CharField(max_length=50)),
                ("url_site", models.URLField()),
                (
                    "docentes",
                    models.ManyToManyField(
                        related_name="licenciaturas", to="portfolio.docente"
                    ),
                ),
            ],
        ),
    ]
