# Generated by Django 6.0.3 on 2026-04-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docente",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="docentes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="licenciaturas",
                to="portfolio.docente",
            ),
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                ("ects", models.IntegerField()),
                ("descricao", models.TextField()),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                (
                    "docentes",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="unidades_curriculares",
                        to="portfolio.docente",
                    ),
                ),
                (
                    "licenciatura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("interesse_pessoal", models.BooleanField(default=False)),
                ("link_site", models.URLField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                (
                    "unidades_curriculares",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="tecnologias",
                        to="portfolio.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
