# Generated by Django 6.0.3 on 2026-04-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_competencia_projeto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenciatura",
            name="docentes",
            field=models.ManyToManyField(
                blank=True, related_name="licenciaturas", to="portfolio.docente"
            ),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="unidades_curriculares",
            field=models.ManyToManyField(
                blank=True, related_name="tecnologias", to="portfolio.unidadecurricular"
            ),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="docentes",
            field=models.ManyToManyField(
                blank=True, related_name="unidades_curriculares", to="portfolio.docente"
            ),
        ),
    ]
