# Generated by Django 6.0.3 on 2026-04-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_formacao_tfc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tfc",
            old_name="descricao",
            new_name="resumo",
        ),
        migrations.RemoveField(
            model_name="tfc",
            name="link_doc",
        ),
        migrations.AddField(
            model_name="tfc",
            name="autores",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tfc",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tfc",
            name="pdf",
            field=models.URLField(blank=True, null=True),
        ),
    ]
