# Generated by Django 6.0.3 on 2026-04-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_rename_descricao_tfc_resumo_remove_tfc_link_doc_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="semestre",
            field=models.CharField(max_length=20),
        ),
    ]
