# Generated by Django 6.0.3 on 2026-04-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_alter_unidadecurricular_semestre"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.TextField()),
                ("descricao", models.TextField()),
                ("erros_correcoes", models.TextField(blank=True)),
                ("foto_papel", models.ImageField(blank=True, upload_to="makingof/")),
                ("uso_ia", models.TextField(blank=True)),
                ("data_relatorio", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
